services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dash
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000/predict